import subprocess
from app.database.database import get_firewall_rules


class NftablesManager:
    """
    Interface between the firewall application and Linux nftables.

    Responsible for:
    - Creating the firewall table
    - Creating base chains
    - Deploying firewall rules
    - Deleting firewall rules
    - Configuring forwarding
    - Configuring NAT
    - Reading the active ruleset
    - Reading packet/byte counters
    """

    TABLE_FAMILY = "inet"
    TABLE_NAME = "firewall_project"

    NAT_TABLE_FAMILY = "ip"
    NAT_TABLE_NAME = "firewall_nat"

    # =========================================================
    # COMMAND EXECUTION
    # =========================================================

    def _run(self, command: list[str], sudo: bool = False) -> str:
        """Execute a system command and return stdout."""

        if sudo:
            command = ["sudo"] + command

        result = subprocess.run(
            command,
            capture_output=True,
            text=True,
        )

        if result.returncode != 0:
            raise RuntimeError(
                f"Command failed:\n"
                f"{' '.join(command)}\n\n"
                f"{result.stderr.strip()}"
            )

        return result.stdout.strip()

    # =========================================================
    # GENERAL
    # =========================================================

    def version(self) -> str:
        """Return the installed nftables version."""

        return self._run(["nft", "--version"])

    # =========================================================
    # FIREWALL TABLE
    # =========================================================

    def table_exists(self) -> bool:
        """Check whether the firewall table exists."""

        result = subprocess.run(
            [
                "sudo",
                "nft",
                "list",
                "table",
                self.TABLE_FAMILY,
                self.TABLE_NAME,
            ],
            capture_output=True,
            text=True,
        )

        return result.returncode == 0

    def create_table(self) -> None:
        """Create the firewall table if it does not exist."""

        if not self.table_exists():
            self._run(
                [
                    "nft",
                    "add",
                    "table",
                    self.TABLE_FAMILY,
                    self.TABLE_NAME,
                ],
                sudo=True,
            )

    def get_ruleset(self) -> str:
        """Return the active firewall ruleset."""

        return self._run(
            [
                "nft",
                "list",
                "table",
                self.TABLE_FAMILY,
                self.TABLE_NAME,
            ],
            sudo=True,
        )

    def flush(self) -> None:
        """
        Remove all rules from the firewall table.

        The table and its chains remain.
        """

        if self.table_exists():
            self._run(
                [
                    "nft",
                    "flush",
                    "table",
                    self.TABLE_FAMILY,
                    self.TABLE_NAME,
                ],
                sudo=True,
            )

    def remove(self) -> None:
        """Delete the complete firewall table."""

        if self.table_exists():
            self._run(
                [
                    "nft",
                    "delete",
                    "table",
                    self.TABLE_FAMILY,
                    self.TABLE_NAME,
                ],
                sudo=True,
            )

    # =========================================================
    # BASE CHAINS
    # =========================================================

    def create_base_chains(self) -> None:
        """
        Create nftables base chains.

        input:
            Traffic destined for the firewall itself.

        output:
            Traffic generated by the firewall itself.

        forward:
            Traffic routed through the firewall.

        Forwarding uses DROP as the default policy.
        """

        chains = {
            "input": ("input", "accept"),
            "output": ("output", "accept"),
            "forward": ("forward", "drop"),
        }

        for chain_name, (hook, policy) in chains.items():

            result = subprocess.run(
                [
                    "sudo",
                    "nft",
                    "list",
                    "chain",
                    self.TABLE_FAMILY,
                    self.TABLE_NAME,
                    chain_name,
                ],
                capture_output=True,
                text=True,
            )

            if result.returncode != 0:

                self._run(
                    [
                        "nft",
                        "add",
                        "chain",
                        self.TABLE_FAMILY,
                        self.TABLE_NAME,
                        chain_name,
                        "{",
                        "type",
                        "filter",
                        "hook",
                        hook,
                        "priority",
                        "0",
                        ";",
                        "policy",
                        policy,
                        ";",
                        "}",
                    ],
                    sudo=True,
                )

    # =========================================================
    # RULE GENERATION
    # =========================================================

    def build_rule_expression(self, rule) -> list[str]:
        """
        Convert a FirewallRule object into nftables arguments.
        """

        expression = []

        # -----------------------------------------------------
        # Source IP
        # -----------------------------------------------------

        if rule.source_ip and rule.source_ip.lower() != "any":
            expression.extend(
                [
                    "ip",
                    "saddr",
                    rule.source_ip,
                ]
            )

        # -----------------------------------------------------
        # Destination IP
        # -----------------------------------------------------

        if rule.destination_ip and rule.destination_ip.lower() != "any":
            expression.extend(
                [
                    "ip",
                    "daddr",
                    rule.destination_ip,
                ]
            )

        # -----------------------------------------------------
        # Protocol
        # -----------------------------------------------------

        protocol = rule.protocol.lower()

        if protocol != "any":
            expression.append(protocol)

        # -----------------------------------------------------
        # Source Port
        # -----------------------------------------------------

        if rule.source_port is not None:
            expression.extend(
                [
                    "sport",
                    str(rule.source_port),
                ]
            )

        # -----------------------------------------------------
        # Destination Port
        # -----------------------------------------------------

        if rule.destination_port is not None:
            expression.extend(
                [
                    "dport",
                    str(rule.destination_port),
                ]
            )

        # -----------------------------------------------------
        # Counter
        # -----------------------------------------------------

        expression.append("counter")

        # -----------------------------------------------------
        # Action
        # -----------------------------------------------------

        if rule.action == "allow":
            expression.append("accept")

        elif rule.action == "deny":
            expression.append("drop")

        else:
            raise ValueError(
                f"Unsupported firewall action: {rule.action}"
            )

        return expression

    # =========================================================
    # ADD RULE
    # =========================================================
    def add_rule(self, rule, chain: str = "forward") -> int | None:
        """
        Add a FirewallRule to nftables according to priority
        and return the newly-created nftables rule handle.
        """

        if not rule.enabled:
            return None

        expression = self.build_rule_expression(rule)

        if not expression:
            raise ValueError(
                f"Rule {rule.id} generated an empty nftables expression."
            )

        # Get existing rules before adding the new rule
        before_rules = self.get_forward_rule_details()

        before_handles = {
            item["handle"]
            for item in before_rules
            if item.get("handle") is not None
        }

        database_rules = get_firewall_rules()

        # -------------------------------------------------
        # Determine insertion position using priority
        # -------------------------------------------------

        insert_handle = None

        for existing_rule in before_rules:

            existing_handle = existing_rule.get("handle")

            if existing_handle is None:
                continue

            database_rule = next(
                (
                    item
                    for item in database_rules
                    if item.get("nft_handle") == existing_handle
                ),
                None
            )

            if database_rule is None:
                continue

            existing_priority = database_rule.get(
                "priority",
                100
            )

            if existing_priority > rule.priority:
                insert_handle = existing_handle
                break

        # -------------------------------------------------
        # Build nftables command
        # -------------------------------------------------

        if insert_handle is not None:

            command = [
                "nft",
                "insert",
                "rule",
                self.TABLE_FAMILY,
                self.TABLE_NAME,
                chain,
                "position",
                str(insert_handle),
                *expression,
            ]

        else:

            command = [
                "nft",
                "add",
                "rule",
                self.TABLE_FAMILY,
                self.TABLE_NAME,
                chain,
                *expression,
            ]

        self._run(command, sudo=True)

        # -------------------------------------------------
        # Detect newly-created handle
        # -------------------------------------------------

        after_rules = self.get_forward_rule_details()

        after_handles = {
            item["handle"]
            for item in after_rules
            if item.get("handle") is not None
        }

        new_handles = after_handles - before_handles

        if not new_handles:
            raise RuntimeError(
                "Rule was added to nftables, but its new handle "
                "could not be determined."
            )

        if len(new_handles) > 1:
            raise RuntimeError(
                f"Multiple new nftables handles detected: {new_handles}"
            )

        return new_handles.pop()


    # =========================================================
    # DELETE RULE
    # =========================================================

    def delete_rule(self, handle: int, chain: str = "forward") -> None:
        """
        Delete an nftables rule using its rule handle.
        """

        command = [
            "nft",
            "delete",
            "rule",
            self.TABLE_FAMILY,
            self.TABLE_NAME,
            chain,
            "handle",
            str(handle),
        ]

        self._run(command, sudo=True)

    # =========================================================
    # STATEFUL FIREWALL
    # =========================================================

    def add_stateful_forward_rules(self) -> None:
        """
        Allow packets belonging to established or related
        connections.
        """

        self._run(
            [
                "nft",
                "add",
                "rule",
                self.TABLE_FAMILY,
                self.TABLE_NAME,
                "forward",
                "ct",
                "state",
                "established,related",
                "accept",
            ],
            sudo=True,
        )

    def add_lan_forward_rule(self, lan_interface: str) -> None:
        """
        Allow new connections originating from the LAN.

        NOTE:
        This method exists for future use but should not be
        called when YAML/API rules are intended to control
        forwarding policy.
        """

        self._run(
            [
                "nft",
                "add",
                "rule",
                self.TABLE_FAMILY,
                self.TABLE_NAME,
                "forward",
                "iifname",
                lan_interface,
                "accept",
            ],
            sudo=True,
        )

    # =========================================================
    # NAT
    # =========================================================

    def nat_table_exists(self) -> bool:
        """Check whether the NAT table exists."""

        result = subprocess.run(
            [
                "sudo",
                "nft",
                "list",
                "table",
                self.NAT_TABLE_FAMILY,
                self.NAT_TABLE_NAME,
            ],
            capture_output=True,
            text=True,
        )

        return result.returncode == 0

    def create_nat_table(self) -> None:
        """Create the IPv4 NAT table."""

        if not self.nat_table_exists():
            self._run(
                [
                    "nft",
                    "add",
                    "table",
                    self.NAT_TABLE_FAMILY,
                    self.NAT_TABLE_NAME,
                ],
                sudo=True,
            )

    def configure_nat(
        self,
        wan_interface: str,
        lan_network: str = "192.168.50.0/24",
    ) -> None:
        """
        Configure IPv4 masquerading for the LAN network.

        LAN traffic leaving through the WAN interface is
        source-NATed to the firewall's WAN address.
        """

        self.create_nat_table()

        # -----------------------------------------------------
        # Check whether postrouting chain exists
        # -----------------------------------------------------

        result = subprocess.run(
            [
                "sudo",
                "nft",
                "list",
                "chain",
                self.NAT_TABLE_FAMILY,
                self.NAT_TABLE_NAME,
                "postrouting",
            ],
            capture_output=True,
            text=True,
        )

        if result.returncode != 0:

            self._run(
                [
                    "nft",
                    "add",
                    "chain",
                    self.NAT_TABLE_FAMILY,
                    self.NAT_TABLE_NAME,
                    "postrouting",
                    "{",
                    "type",
                    "nat",
                    "hook",
                    "postrouting",
                    "priority",
                    "100",
                    ";",
                    "policy",
                    "accept",
                    ";",
                    "}",
                ],
                sudo=True,
            )

        # -----------------------------------------------------
        # Flush old NAT rules
        # -----------------------------------------------------

        self._run(
            [
                "nft",
                "flush",
                "chain",
                self.NAT_TABLE_FAMILY,
                self.NAT_TABLE_NAME,
                "postrouting",
            ],
            sudo=True,
        )

        # -----------------------------------------------------
        # Add masquerade rule
        # -----------------------------------------------------

        self._run(
            [
                "nft",
                "add",
                "rule",
                self.NAT_TABLE_FAMILY,
                self.NAT_TABLE_NAME,
                "postrouting",
                "oifname",
                wan_interface,
                "ip",
                "saddr",
                lan_network,
                "masquerade",
            ],
            sudo=True,
        )

    # =========================================================
    # STATUS / DEBUGGING
    # =========================================================

    def get_nat_ruleset(self) -> str:
        """Return the active NAT ruleset."""

        if not self.nat_table_exists():
            return ""

        return self._run(
            [
                "nft",
                "list",
                "table",
                self.NAT_TABLE_FAMILY,
                self.NAT_TABLE_NAME,
            ],
            sudo=True,
        )

    # =========================================================
    # COUNTERS
    # =========================================================

    def get_forward_counters(self) -> str:
        """
        Return the current FORWARD chain including
        packet and byte counters.
        """

        return self._run(
            [
                "nft",
                "-a",
                "list",
                "chain",
                self.TABLE_FAMILY,
                self.TABLE_NAME,
                "forward",
            ],
            sudo=True,
        )

    def get_rule_counters(self):
        """
        Return structured packet and byte counters
        for rules in the FORWARD chain.
        """

        output = self._run(
            [
                "nft",
                "-a",
                "list",
                "chain",
                self.TABLE_FAMILY,
                self.TABLE_NAME,
                "forward",
            ],
            sudo=True,
        )

        counters = []

        for line in output.splitlines():
            line = line.strip()

            if "counter packets" not in line:
                continue

            parts = line.split()

            try:
                packets_index = parts.index("packets")
                bytes_index = parts.index("bytes")

                packets = int(parts[packets_index + 1])
                bytes_count = int(parts[bytes_index + 1])

            except (ValueError, IndexError):
                continue

            action = None

            if " accept" in f" {line} ":
                action = "accept"

            elif " drop" in f" {line} ":
                action = "drop"

            counters.append(
                {
                    "rule": line,
                    "packets": packets,
                    "bytes": bytes_count,
                    "action": action,
                }
            )

        return counters

    # =========================================================
    # RULE DETAILS
    # =========================================================

    def get_forward_rule_details(self):
        """
        Return detailed information about rules
        in the FORWARD chain.
        """

        output = self._run(
            [
                "nft",
                "-a",
                "list",
                "chain",
                self.TABLE_FAMILY,
                self.TABLE_NAME,
                "forward",
            ],
            sudo=True,
        )

        rules = []

        for line in output.splitlines():
            line = line.strip()

            if "counter packets" not in line:
                continue

            parts = line.split()

            try:
                packets_index = parts.index("packets")
                bytes_index = parts.index("bytes")

                packets = int(parts[packets_index + 1])
                bytes_count = int(parts[bytes_index + 1])

            except (ValueError, IndexError):
                continue

            handle = None

            if "# handle" in line:
                try:
                    handle = int(
                        line.split("# handle")[1].strip()
                    )
                except ValueError:
                    pass

            if " accept" in f" {line} ":
                action = "accept"

            elif " drop" in f" {line} ":
                action = "drop"

            else:
                action = "unknown"

            rules.append(
                {
                    "handle": handle,
                    "packets": packets,
                    "bytes": bytes_count,
                    "action": action,
                    "rule": line,
                }
            )

        return rules